### ISSUE TITLE
lvmd daemonset

### ISSUE THREAD

**Issue by kfox1111** [topolvm/topolvm#195]
## What
It would be nice if you could deploy lvmd with Kubernetes

## How
lvmd should be deployable thusly:
* shipping lvmd & nsenter in a container
* setting the lvmd pod to hostPID: true (so it can see pid1 on the host)
* setting the lvmd pod to be privileged (so it can use nsenter)
* mounting /bin or some other directory from the host into the container at /hostbin as writable
* copying lvmd to /hostbin
* running: nsenter -t 1 -a /bin/lvmd (startup lvmd on the host)

It should then run lvmd as if it was on the host as all the containerization will be stripped back to the namespaces associated with the hosts pid1 process.

## Checklist

- [x] Finish implementation of the issue
- [ ] Test all functions
- [ ] Write some documents for this change
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by llamerada-jp** [comment]
Hi @kfox1111 

I'm very excited about your idea. I think it requires some improvement for the following reasons.
- Some distributions prohibit write to system directories like `/bin`.
- Running `lvmd` as a whole with `nsenter -t 1` completely breaks the container boundary.
  It loses the benefit of container separation, for example, it suffers from a collision of a listening port.

Instead of running `lvmd` in the host namespaces, I'd like to call `lvm` and `blockdev` commands
with `nsenter -t 1 -a` from inside `lvmd`. In this way, we can avoid the above problems.
What do you think about this improvement?

**Comment by kfox1111** [comment]
It breaks the container boundry, but that is often done with really low level containers such as calico where it copies binaries on to the host to make cni work, or some of the host upgrade orchestration containers. Arguably this use case fits that use case. Low level storage access.

I had looked through the code yesterday and noticed it could probably be done by wrapping the exec of the lvm and blockdev commands with nsenter. But I was not sure there wasn't any other functions in the code base accessing things directly that would need to have the same view as the host. It would take good knowledge of the code base to decide if that was safe.

I did get a very rough prototype working and emailed it to @ymmt2005. Not sure what the best way to integrate it with the rest of the code. maybe an overlay

In the prototype I put it in /usr/libexec/lvmd as that is the FHS standard location for those sorts of things. Your right, it may not be writable though. It probably needs to be made configurable. That kind of configurability can be harder to do with kustomize then something like helm. Which is probably a whole other discussion. (The clusterrole names are questionable in my environment...)

**Comment by llamerada-jp** [comment]
I looked at your manifest file posted on slack. I agree that breaking the container boundary is suitable for our use case, low-level storage access. And I want to minimize the scope of that instead of all of `lvmd`.

Our team is willing to provide enough support to you when modifying the lvmd code base.
> I was not sure there wasn't any other functions in the code base accessing things directly that would need to have the same view as the host. 

I think we only need to change calls of  `lvm` and `blockdev`. I'll investigate the concerns more deeply.

**Comment by kfox1111** [comment]
Ok, then I think the next steps are:
1. PR that adds lvmd to the container. I don't think there will be a time when you don't want to deploy the lvmd but you do want the node agent. So bundling together is ok.
2. PR that adds a --containerized flag to lvmd that causes lvm and blockdev commands to be wrapped with nsenter
3. PR adding lvmd daemonset support

This sound like an ok plan?

**Comment by ymmt2005** [comment]
@kfox1111 
Sounds good!  Please move forward.

**Comment by llamerada-jp** [comment]
Hi @kfox1111 
How are you getting on? May I help you if you have some problems with this issue?

**Comment by kfox1111** [comment]
Sorry, I kind of stalled out on this. Its Fiscal Year End for us right now so will probably free up in a week or two. If you want to make PR's for any of the above tasks, please go for it.

**Comment by llamerada-jp** [comment]
It's OK. You don't need to hurry.

**Comment by kfox1111** [comment]
#1 looks to already be done. there is a symlink to /lvmd to /hypertopolvm in the container already and seems to look correct when given a --help.

**Comment by kfox1111** [comment]
Got a working prototype working. I don't know kustomize very well yet so I just did the work on the helm chart, as I do know helm well.

**Comment by ymmt2005** [comment]
@kfox1111 
Great work!  We can help kustomize parts.

**Comment by aneagoe** [comment]
Thanks a lot for this, it should further simplify the deployment.

**Comment by skaegi** [comment]
This is great stuff, but I wanted to understand if there is a particular reason to use nsenter instead of copying the files to the host. We use both calico and kata containers where that approach has worked well. I'm very familiar with the approach used in kata -- https://github.com/kata-containers/kata-containers/blob/2.0-dev/tools/packaging/kata-deploy/kata-deploy/base/kata-deploy.yaml -- and would like to help here, but don't want to derail the effort with a different approach.

**Comment by kfox1111** [comment]
Both kata and calico is a little different in that external things on the system, outside of the containers, are needing to execute programs. Flow of execution starts at the host.

cni needs to execute the calico plugin so it can only execute things on the host so it needs to be copied onto the host.

the container engine (containerd, crio, etc) also execs the container runtime so it needs to be on the host. so it gets copied to the host.

lvmd is a long running service contactable via unix socket. so it does not need to be copied onto the host for something to start it. The container itself can start it.

**Comment by little-guy-lxr** [comment]
> Hi @kfox1111
> 
> I'm very excited about your idea. I think it requires some improvement for the following reasons.
> 
> * Some distributions prohibit write to system directories like `/bin`.
> * Running `lvmd` as a whole with `nsenter -t 1` completely breaks the container boundary.
>   It loses the benefit of container separation, for example, it suffers from a collision of a listening port.
> 
> Instead of running `lvmd` in the host namespaces, I'd like to call `lvm` and `blockdev` commands
> with `nsenter -t 1 -a` from inside `lvmd`. In this way, we can avoid the above problems.
> What do you think about this improvement?
in container report a error
nsenter: cannot open /proc/1/ns/cgroup: No such file or directory

and I check host OS and did not found /proc/1/ns/cgroup namespace cgroup why not foud ?

**Comment by toshipp** [comment]
Design ideas for deploying `lvmd` daemonset.

If you run `lvmd` with daemonset, you may have a requirement to change `lvmd.conf` for each node.
In this case, you can use the node selector to deploy a different daemonset, so that
you can specify multiple configurations.
Alternatively, you can configure `lvmd.conf` separately for each node and use a single daemonset with hostPath specified.

**Comment by toshipp** [comment]
How to migrate to Lvmd daemonset.

1. Set the socket-name of the containerized lvmd to something different from the socket-name of the host lvmd, and apply daemonset.
2. Change the socket-name of topolvm-node to that of the containerized lvmd, and apply manifest.

**Comment by toshipp** [comment]
Hi @matthias50,
We designed how to migrate to daemonset deployment as above.
Would you let me know if you have an opinion?

**Comment by kfox1111** [comment]
> Design ideas for deploying `lvmd` daemonset.
> 
> If you run `lvmd` with daemonset, you may have a requirement to change `lvmd.conf` for each node.
> In this case, you can use the node selector to deploy a different daemonset, so that
> you can specify multiple configurations.
> Alternatively, you can configure `lvmd.conf` separately for each node and use a single daemonset with hostPath specified.

In the helm chart, I put the lvm daemonset & configmap in a loop, so you could specify multiple instances with different config and node selectors.

**Comment by matthias50** [comment]
@toshipp  We consider our nodes to be immutable infrastructure. When we want to upgrade the cluster in the cloud, we terminate all the nodes in sequence and let them be re-created from scratch. So anything which flat out requires updating nodes in place is a no-go for us.  My thought is that we could do this migration by having the lvmd daemonset contain a node selector which would target nodes with some label which "old" nodes would lack, but the "new" nodes would have.

The "new" nodes would not have lvmd running locally but would have the label, so the daemonset would only run on these nodes. Then once all nodes have been cycled, the migration would be complete.

**Comment by toshipp** [comment]
@kfox1111 @matthias50 
Thank you for sharing your thought!
We will work this way.

**Comment by satoru-takeuchi** [comment]
closed by #285
