### ISSUE TITLE
base image

### ISSUE THREAD

**Issue by kfox1111** [topolvm/topolvm#197]
**Describe the bug**
Is there a reason to base the container FROM quay.io/cybozu/ubuntu:18.04 rather then the official ubuntu?

As its a go based build, would alpine or distroless be even better (smaller)?

**Comment by ymmt2005** [comment]
The container image needs to be a full-fledged distribution because TopoLVM
invokes `mkfs.ext4` or similar filesystem making commands.

The reason why we are using `quay.io/cybozu/ubuntu:18.04` is historical.
That image is maintained and updated by the maintainers from Cybozu.

We can replace the base image with the official one.

**Comment by kfox1111** [comment]
alpine would still work I think if we added the appropriate mkfs.* commands. It should still be significantly smaller then the ubuntu container I think.

standard ubuntu container would still be nice though.
