### ISSUE TITLE
low kernel version not support  cgroup namespace that nsenter -a has error

### ISSUE THREAD

**Issue by little-guy-lxr** [topolvm/topolvm#231]
**Describe the bug**
when container start, nsenter -a command has error, not found cgroup namespace, because host kernel is 3.10 not support

**Environments**
- Version: 1.1.1
- OS: linux 3.10

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by llamerada-jp** [comment]
Hi @little-guy-lxr ,

We do not intend to extend our support for guaranteed kernel versions. That said, we understand that `nsenter -a` would cause trouble like this. We'll fix it after testing lvmd containerization.
However, since we cannot test on an old kernel, could you please consider upgrading the kernel?

**Comment by little-guy-lxr** [comment]
> Hi @little-guy-lxr ,
> 
> We do not intend to extend our support for guaranteed kernel versions. That said, we understand that `nsenter -a` would cause trouble like this. We'll fix it after testing lvmd containerization.
> However, since we cannot test on an old kernel, could you please consider upgrading the kernel?

ok, now my workaround is  

args = append([]string{"-u", "-i", "-n", "-m", "-p", "-t", "1", cmd}, args...)
//args = append([]string{Param, cmd}, args...)

**Comment by toshipp** [comment]
closed via #364
