### ISSUE TITLE
CSI volume health support?

### ISSUE THREAD

**Issue by arianvp** [topolvm/topolvm#316]
**What should the feature do:**

https://kubernetes.io/blog/2021/04/16/volume-health-monitoring-alpha-update/

It would be nice if TopoLVM adds support for volume health monitoring. This could detect broken hardware (Bad SMART values?) and mark PVCs accordingly

**What is use case behind this feature:**

Detect if nodes or volumes have gone bad; so that I can act on it

**Comment by toshipp** [comment]
LVM is a virtual block device and its lower device can be also virtual devices (Of course, they can be actually physical devices such as HDD or SSD). So, if topolvm support the feature, we should implement that device neutral health support is needed. It would need a bit harder engineering and cause error-prone alerts, IMO. I think it is better to monitor physical devices directly.

**Comment by arianvp** [comment]
Perhaps as a first step we could feature gate it to LVM volumes that are
backed by a physical device only? Then SMART monitoring and `badblocks` can
be used reliably .

But even for hardware there is no generic solution. E.g. for Nvme devices
you need to use the Nvme command for SMART data retrieval.

**Comment by toshipp** [comment]
I do not agree to monitor physical devices by topolvm. The knowledge of whether the device is bad or not is not related to topolvm.

Here is a just idea; A lvm volume has an attribute that is active or inactive.  Topolvm reports it by CSI volume health. If some physical device used by a lvm volume is "bad", some component detects such condition and in-activate the lvm volume.

BTW, did you face a problem detecting a root cause using TopoLVM? Would you let me know your real problem?
