### ISSUE TITLE
topolvm's image can support multiple systems

### ISSUE THREAD

**Issue by attlee-wang** [topolvm/topolvm#369]
**What should the feature do:**
I use topolvm on the arm machine with the following problems

![image](https://user-images.githubusercontent.com/57479557/135027044-943eddfe-b2f4-4988-9343-9a75b94e598d.png)

**What is use case behind this feature:**

topolvm's image can support multiple systems

**Comment by llamerada-jp** [comment]
hi @attlee-wang 

If you want to use TopoLVM in ARM environment, would you please create the image for ARM environment and verify it by yourself. Supporting ARM environment has been put on hold for the following reasons.
- We don't have an ARM environment and can't verify behavior or do CI.
- Development to support docker-buildx has stalled due to the above reason.
  ref. https://github.com/topolvm/topolvm/pull/217

**Comment by toshipp** [comment]
merge to #378
