### ISSUE TITLE
cluster-autoscaler doesn't scale up when Pods are Pending due to space exhaustion

### ISSUE THREAD

**Issue by matthias50** [topolvm/topolvm#39]
**Describe the issue** 
I logged this as an issue, not a bug because it looks more like a potential new feature. The issue I am facing if pods get into the Pending state because there is no more space left for them on any node for a lvm, the pods get stuck there and the cluster-autoscaler, https://github.com/kubernetes/autoscaler doesn't kick in to add a node.

**Environments**
- Version: Any
- OS: Any

**To Reproduce**
1. Create pods with PVCs until storage is exhausted on all nodes
2. Observe pending pods.

**Expected behavior**
cluster-autoscaler detects the condition and adds nodes.

**Additional context**
I think this happens because cluster-autoscaler is running a scheduler simulation to see if it needs to add pods. Since topolvm-scheduler is a scheduler extender, it won't be a part of the simulation cluster-autoscaler runs..

**Comment by snigdhasambitak** [comment]
Because storage capacity gets published by a running CSI driver and the cluster autoscaler needs information about a node that hasn't been created yet, it will currently not scale up a cluster for pods that need volumes. Seems like [there is an idea ](https://github.com/kubernetes/autoscaler/pull/3887) how to provide that information which is WIP
