### ISSUE TITLE
Set up Tilt for TopoLVM

### ISSUE THREAD

**Issue by lentzi90** [topolvm/topolvm#405]
**What should the feature do:**
A [Tiltfile](https://github.com/tilt-dev/tilt) should be added that allows developers to set up a complete development environment with smart rebuilds and automatic updates to TopoLVM running in e.g. KinD or minikube.

**What is use case behind this feature:**
I think using Tilt would help developers iterate fast while also testing things in e2e fashion. To my understanding (I'm new to the project) there isn't really a way to test things "live" right now. There are e2e tests, but they take time and may be tricky to debug. With Tilt I believe it would be easier to test and play with TopoLVM in a more interactive manner.

If there is interest in this I may be able to help set things up. :slightly_smiling_face:

**Comment by llamerada-jp** [comment]
I read tilt's document a little. I believe that we will be limited in what we can test if we use tilt. We make sure that each module has been successfully deployed when running TopoLMV's e2e. Therefore, I think we need a clean environment to re-run the tests. This is also because we are deleting a part of node in the e2e test.
Additionally, building an e2e environment for TopoLVM is tricky because of the presence of scheduler and lvmd. I did not find out if tilt supports that level of configuration.
If you want to use tilt for development, we can help, but I don't know if it's feasible.

**Comment by llamerada-jp** [comment]
I think I misunderstood the intent of the issue.  The purpose is simple, to create an e2e runtime environment using Tilt, not including running e2e tests. Is that correct? @lentzi90 

I also misunderstood the configuration of Tilt. If we can attach it to an existing Kubernetes cluster, I think it could be handled by modifying the existing script. For other features, we will need to study them in more detail.

**Comment by lentzi90** [comment]
> I think I misunderstood the intent of the issue. The purpose is simple, to create an e2e runtime environment using Tilt, not including running e2e tests. Is that correct? @lentzi90

Exactly! I think it would be perfect to "experiment" a bit rather than running e2e tests.

**Comment by llamerada-jp** [comment]
It would be great if you create a PR, is it possible? I would appreciate it if you could take care of the following points if possible.
- We want to use the existing cluster startup script with some patches as needed. This is because we want to avoid duplicating it.
- `values.yaml` are different depending on the configuration of the cluster. Is there a better way to handle this by Tilt?
