### ISSUE TITLE
It is long time when  pvc is resized

### ISSUE THREAD

**Issue by huang339** [topolvm/topolvm#496]
## What
It is long time when  pvc is resized, which  last about 2 minute 

## How
it is better the pvc is resize less than 5 second

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by llamerada-jp** [comment]
We would like to receive more information to investigate the cause.
- Are you using pvc-autoresizer? If so, it takes several minutes to detect a change in disk capacity.
- Do you check the logs of csi sidecars and kubelet's logs? For resize process, TopoLVM corporate with csi-sidecar and kubelet. The whole process could take several minutes.

**Comment by huang339** [comment]
it is about 2 minute after the resize pvc success,  the most time is used in 
syncPod
WaitForAttachAndMount
ReprocessPod
markPodProcessingFailed

then it is fast to resize
reconciler reconcile
mountAttachVolumes
    fsResizeRequired==true
    rc.operationExecutor.ExpandInUseVolume

but why ceph csi is very fast to resize pvc

**Comment by llamerada-jp** [comment]
I don't know the actual behavior of ceph CSI. But there are several architectures of CSI drivers like the link below. It may make some difference to the time of resize.
https://github.com/container-storage-interface/spec/blob/master/spec.md#architecture

I guess this issue is not a bug of TopoLVM, I would like to close it if there are no objections.
