### ISSUE TITLE
Support for LVM thin provisioned volumes/pools

### ISSUE THREAD

**Issue by pasikarkkainen** [topolvm/topolvm#73]
Are LVM thin provisioned pools/volumes currently (optionally) supported in topolvm? At least I didn't find any mention of thinprov in the docs.. 

Thanks!

**Comment by ymmt2005** [comment]
Thin-provisioned volumes are not supported off the shelf because
`lvmd`, an underlying gRPC service to run LVM commands, does not
use thin-pools.

You can replace `lvmd` with anything that implements [the same protocol](https://github.com/cybozu-go/topolvm/blob/master/lvmd/proto/lvmd.proto)
to use thin-pools or even to use `losetup` on normal files.

If you want to add support for thin-provisioning to `lvmd`, we welcome your
pull request.  A good first issue, I think.

**Comment by nwmcsween** [comment]
This is also needed to snapshot functionality IIRC

**Comment by toshipp** [comment]
LVM provides snapshot functionality in two ways; by dm-snapshot or dm-thin.
topolvm now uses dm-linear, which can provide snapshot functionality by dm-snapshot.

**Comment by toshipp** [comment]
working on #448
