### ISSUE TITLE
Feature Request: Support disk encryption using LUKS

### ISSUE THREAD

**Issue by ryanfaircloth** [topolvm/topolvm#828]
While IAAS providers such as aws and azure encrypt storage other operating environments such as on premise data centers and edge computing are less likely to have effective hardware protected encryption. The feature request is certainly non trival but using luks with server level TPM2 as one key shard component and a cluster level secret key as the second component provide encryption on local storage. This model ensure that a single node removed from the cluster or the cluster level key on their own can not be used to decrypt data.

This is something I might be interested in working on myself I presently don't have available time but I think this feature would be compelling.

**Comment by pluser** [comment]
Thanks for the feature suggestion.

Disk encryption is interesting. However, could we solve this problem by providing a layer such as LUKS under LVM? If TopoLVM itself has the ability to work with LUKS, I am concerned that there are several things to consider, such as key distribution, and the implementation may be complex.

**Comment by ryanfaircloth** [comment]
@pluser I think that approach would even be desirable its certainly not as simple as "set a variable to turn it on" key management is critical needs to be thought out and done well.

**Comment by jakobmoellerdev** [comment]
Hey guys, just adding my 2 cents here: What does "disk encryption support" even mean? We can already today establish volume groups based on LUKS transparently encrypted disks and use them in TopoLVM by simply referencing the encrypted Disk path.

Similarly it is possible already today to create a PVC and then use this as a block storage device in a Pod an bind it via tooling into application level encryption through App level LUKS by providing cryptsetup capabilities in the Pod.

The only thing that is not possible right now is automated App-Level encryption with LUKS based on workload. Due to the use cases for TopoLVM (local storage provider), IMO We dont need to add Key Management Capabilities into TopoLVM for this third case because serious users will anyhow encrypt their disks externally and transparently without storing the crypto material or access to it in the cluster where TopoLVM would be able to use it.

**Comment by ryanfaircloth** [comment]
I think providing crypto in the pod would be improper for similar reasons to not providing the ability to format a block device. The concern of encryption is independent of the application and should be kept separated.  Each lv should be encrypted with its own keys when deleted the keys would be removed providing instant secure delete. This solution uses clevis at the block level, there are other possible implementations the ideal solution would be logical volume level for data drives
Likely two modes
"TPM only" which would leverage the TPM alone
TPM + secret would require TANG which could be in cluster or out of cluster essentially binding the drives to the node and network 
https://fedoramagazine.org/using-linux-system-roles-to-implement-clevis-and-tang-for-automated-luks-volume-unlocking/

**Comment by jakobmoellerdev** [comment]
> I think providing crypto in the pod would be improper for similar reasons to not providing the ability to format a block device. The concern of encryption is independent of the application and should be kept separated.
+1 to that.

TPM only already is supported on disk level: Here is a high level blog article on usage: https://www.redhat.com/en/blog/encryption-rest-red-hat-openshift-application-data-edge

TPM + secret with TANG should be possible via the same way if we configure it in advance on the block device.

My question is rather: For a local storage provisioning operator, what is the benefit of LV level encryption if we can just encrypt the entire disk and have all LVs be encrypted ootb?

We can still pass the encrypted device via block storage mode to the pods or create fs on top.

My point being: For a non-distributed local storage provider, why support LV-level encryption/decryption?

**Comment by ryanfaircloth** [comment]
in a multi tenant cluster PV level encryption does not meet all of the appropriate security check boxes
* LVM PV the life cycle is the node not the instance
* when a PVC is removed the partition contents should be unrecoverable to achieve that one possibility is secure erase on removal which can be time consuming and depending on underlying storage technology both ineffective or damaging to the hardware. When a LV is specifically encrypted destruction of the key is considered effective secure erasure. Secure erase is also something you have to audit and manage to follow up and resolve issues in the process. With LV level encryption the process is resistant to such failures.

**Comment by jakobmoellerdev** [comment]
Ack to these suggestions and agreed. Do we know of people using multi tenant PV encryption with LVMS? Would be cool to get feedback from people interested in this use case.

**Comment by ryanfaircloth** [comment]
To my knowledge the only two LVM based local provisioners are topolvm and openEBS "ndm". In the enterprise world encryption and storage management for local disk is almost always vmware. I see this feature as a potential unblocker for k8s on bare metal and kubevirt as local encryption is areal need for enterprise deployments. Other use cases like edge and IOT It could help but the the ultimate protection of the keys is a larger challenge

**Comment by jakobmoellerdev** [comment]
So I can contribute to this discussion of Edge/IoT and I can guarantee that most deployers will only be caring about disk level encryption as there is no use case for multi tenancy there.
Encryption / Storage Management for local disk is usually done low level on these machines and they do not get managed via vmware software/hardware but via hardware raid that is encrypted via TPM.
This (at least for our known OpenShift Users) is not a blocker for k8s on bare metal. Kubevirt clusters should imo not run on local storage because they will loose the scalability factor of the underlying cluster.

That said, if we can find an easy (enough) way to implement this in the existing codebase, im all for supporting more use cases.

**Comment by ryanfaircloth** [comment]
Certainly needs some investigation and design. In the kube-virt use case for latency sensitive workloads, and honestly the workloads I would ever use localpv for regardless of being in container or VM the data on the disk is replicated at the application level not the hypervisor level so we don't loose scalability at all. Now there is another type of workload where I might use openEBS Maya or a number of other options for clustered block storage or storage networking which would all be non goals for this project
