### ISSUE TITLE
Project Status: Testing for production?

### ISSUE THREAD

**Issue by guettli** [topolvm/topolvm#885]
The readme says 

> Project Status: Testing for production

Afaik this is wrong 

Topolvm is used in production for several months.

**Comment by daichimukai** [comment]
Hi, @guettli.

Thank you for letting us know. As you pointed out TopoLVM is already used in the production environments, the project status in README.md  does not reflect the actual status of this project. The current maintainers have agreed to remove this sentence from README.md. This is because the project status decided by the project owners themselves is not very useful and might confuse the readers. I hope it makes sense to you.
