### ISSUE TITLE
Cross-node Snapshot restore

### ISSUE THREAD

**Issue by dhilipkumars** [topolvm/topolvm#957]
Hello Team, 
We are looking to evaluating topolvm and stumbled upon this [limitation](https://github.com/topolvm/topolvm/blob/main/docs/limitations.md#snapshots-can-be-restored-only-on-the-same-node-with-the-source-volume) , wanted to reach out and ask if there is a feature underway or in the roadmap to overcome it. 

**What should the feature do:**
Allow you to restore from snapshots that originated from a different node. 

**What is use case behind this feature:**
- As a DBaaS (Database as a Service) on k8s i want to add a replica to my DB cluster and that replica should start restoring from primary's recent snapshot. (primary and replica scheduled on different node)
- As a DBaaS on k8s I want to move my DB engine to a bigger VM, which should bootstrap by restoring its recent snapshot (which could be from the old smaller host).

**Comment by jakobmoellerdev** [comment]
TopoLVM is a local CSI Driver using your hosts lvm2. To circumvent this limitation (without using a shared volume group, which is not supported by topolvm), one would have to implement a node synchronization mechanism that copies blocks over to other nodes, which is afaik currently not in scope for the driver since it would basically explode its codebase.

It is entirely possible to write such a block synchronization yourself and prepopulate PVs but that must be done outside the driver at the moment.
